### ISSUE TITLE
Support sub directory documents

### ISSUE THREAD

**Issue by mrlee23** [mrlee23/LinuxCommands#3]
# Problems
Currently only 1-level depth documents can be generated without errors or unsuspected behaviors.

On the 6992104de98ef769332ef3f5c1aff5a231f6a2bb commit, activate recursive option but not yet solved the problems.

# Todo
Here's the items to solved in this issue.
- [x] Clean copy only document files to original folder.
- [x] No conflict with not document files. (eg. dist or dependency files)
- [x] Generating the documents of sub directory without missing files and wrong including.
